### ISSUE TITLE
Error when trying to run clone_oca_dependencies

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/maintainer-quality-tools#136]
```bash
[root@51b51934b30d]~/Vauxoo/yoytec$
 (8.0)$ /root/maintainer-quality-tools/travis/clone_oca_dependencies 
Traceback (most recent call last):
  File "/root/maintainer-quality-tools/travis/clone_oca_dependencies", line 122, in <module>
    run(home, build_dir)
  File "/root/maintainer-quality-tools/travis/clone_oca_dependencies", line 80, in run
    for repo in os.listdir(build_dir):
OSError: [Errno 2] No such file or directory: '/root/build/Vauxoo'
```

This occurs when I create a new t2d container for one of our clients.
Before we has path `/root/build/Vauxoo`: now we have `/root/Vauxoo` and this one do not match.

I think we can take advantage of change `/root/Vauxoo` to `/root/vauxoo` (without capitalization) https://github.com/Vauxoo/travis2docker/issues/66

**Comment by moylop260** [comment]
Fixed from t2d https://github.com/Vauxoo/travis2docker/issues/66

We should use the environment variable TRAVIS_BUILD_DIR to get this folder value.

OCA original project use it: https://github.com/OCA/maintainer-quality-tools/blob/25653954bb24244c351ba46c4cf7d3debe0c8fe2/travis/clone_oca_dependencies#L116
