### ISSUE TITLE
[master] maintainer-quality-tools: Use -u with --test-enable in order to avoid errors when a module is installed in isolated way.

### ISSUE THREAD

**Issue by KarenKawaii** [Vauxoo/maintainer-quality-tools#139]
**Related to the issue**
https://github.com/Vauxoo/yoytec/issues/1968 for `yoytec_rma_workflow`

**Steps to reproduce the error in the issue log**
1. `creatdb -T openerp_template yoytec_rma_workflow2`
2. `~/odoo-8.0/odoo.py -d yoytec_rma_workflow2 -i yoytec_rma_workflow --stop-after-init`
3. `~/odoo-8.0/odoo.py -d yoytec_rma_workflow2 -i yoytec_rma_workflow --stop-after-init --test-enable`

**Current behavior**
The warning appears:
```bash
aise osv.except_osv(_('Warning!'), _('Nothing to check the availability for.'))
ParseError: "Warning!
Nothing to check the availability for." while parsing /root/build/Vauxoo/yoytec/yoytec_rma_workflow/demo/purchase_order.xml:332, near
<function model="stock.picking" name="action_assign">
<value eval="obj(ref('purchase_order_rma_1')).picking_ids[0].id" model="purchase.order"/>
</function>
```
**Expected behavior**
No triggered warnings or errors related to the double use of `--init` `module`

**Note:**
The warning for `yoytec_rma_workflow` not happens if you use `--init yoytec_rma_workflow` and then `-u yoytec_rma_workflow`

So, we need to introduce the following change in `mqt`
e.g.,
Instead of:
```bash
-i module
-i module --test-enable
```
should be:
```bash
-i module
-u module --test-enable
```

**Comment by moylop260** [comment]
FYI this fix dont apply for all cases of tests of mqt
Just for the case of test enable

**Comment by KarenKawaii** [comment]
Roger that, to be more clear I will update the e.g. in the description.

Thanks @moylop260
