### ISSUE TITLE
[REF] git-hook: Ask if we want run lints

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/maintainer-quality-tools#163]
Currently we have a pre-commit hook for git:
https://github.com/Vauxoo/maintainer-quality-tools/blob/master/git/pre-commit

But this show many messages without ask before.

A good approach could be ask if you want a lint result from keyboard entry.

`Do you want run lints? (Y/n)` <- default `n`

If `n` (no) is selected then skip this scripts return success code exit

Check the [README](https://github.com/Vauxoo/maintainer-quality-tools/blob/master/git/README.md) to know use it

**Comment by osvalr** [comment]
:+1: 
to know the default value is often used the upper option as the following example:
```bash
Need to get 153 MB of archives.
After this operation, 492 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

**Comment by moylop260** [comment]
Fixed from https://github.com/Vauxoo/maintainer-quality-tools/issues/166
