### ISSUE TITLE
Error when try test PR to Odoo/odoo

### ISSUE THREAD

**Issue by luistorresm** [Vauxoo/maintainer-quality-tools#168]
If I make the next change in .travis file:

`- if [[ "${TESTS}" == "1" ]]; then cd ~/odoo-8.0; git remote add REMOTE URL; git fetch REMOTE BRANCH; git reset --hard REMOTE/BRANCH`

To test a PR in Vauxoo/odoo I get the next error in travis.

![job 1654 2 vauxoo mexico travis ci](https://cloud.githubusercontent.com/assets/7606656/21462737/225b4430-c925-11e6-8b38-81c04985def3.png)

**Comment by moylop260** [comment]
@luistorresm 
Thanks for reporting

@tomeyro 
Could you help me to fix it?

The main issue is that we are using a git repository for odoo from runbot using the docker image https://hub.docker.com/r/vauxoo/odoo-80-image-shippable-auto/
But for travis odoo is download from tar (without git).

The idea is use a git repository for travis too but we need valid if a `git clone --single-branch --depth=1` (faster clone) is compatible with the patch mentioned by @luistorresm
