### ISSUE TITLE
[REF] odoo-shippable: Add the following bash profile items:

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/maintainer-quality-tools#177]
```bash
git_fetch_pr() {
  REMOTE=$1
  shift 1
  git fetch -p $REMOTE +refs/pull/*/head:refs/pull/$REMOTE/*
}
```
```bash
alias rgrep='rgrep -n'
```

And load `source ~/container.profile` file if exists. (currently is not exists, but we can add it from t2d command)

**Comment by JesusZapata** [comment]
@moylop260 
This issue was register in https://github.com/Vauxoo/docker-odoo-image/issues/184
Please, close this issue
