### ISSUE TITLE
Warning is really a error

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/maintainer-quality-tools#185]
<s>Show the CI (travis, gitlab...) red for warning cases, use a regex warning like as runbot
https://github.com/Vauxoo/odoo-extra/blob/50c7a671cbc5cb8150d44f5f3d0bbc428b60ae75/runbot/runbot.py#L47</s>

Better use a gitlab pipeline `warning` to process the log after finish tests

**Comment by moylop260** [comment]
@ruiztulio was developed this feature haha

**Comment by JesusZapata** [comment]
@moylop260 
Ok, thanks
:+1:
