### ISSUE TITLE
[FIX] travis_install_nightly: Error cloning dependencies

### ISSUE THREAD

**Issue by JesusZapata** [Vauxoo/maintainer-quality-tools#188]
@moylop260 

I pull the last imagen `vauxoo/odoo-80-image-shippable-auto` and ran one `t2d`
And show the following error

![image](https://cloud.githubusercontent.com/assets/1387970/23799942/c63dce6e-0580-11e7-9484-4fbc22ad4518.png)

**Comment by JesusZapata** [comment]
I think it is due to the change of the user from root to odoo

**Comment by moylop260** [comment]
I didn't see the t2d command used.
But this is not a change of user from root to odoo issue because our runbot is working fine with this update.

Maybe this is a permission case if you don't can see the project [odoo/enteprise](https://github.com/odoo/enterprise)

Did you try clone locally?

**Comment by JesusZapata** [comment]
@moylop260 

Now works fine thank you

![image](https://cloud.githubusercontent.com/assets/1387970/23854381/8ed8d948-07c7-11e7-984a-cd1e670a1f36.png)
