### ISSUE TITLE
Parameter to specify webkit version that i need to install in my project

### ISSUE THREAD

**Issue by suniagajose** [Vauxoo/maintainer-quality-tools#204]
Currently MQT installs 0.12.3 of wkhtmltopdf.

In some cases we need another version, but there is no other option to change this unless we explicitly indicate it in our repository.

Like this:
https://github.com/Vauxoo/inteco/pull/103/files

It is desirable that by means of a parameter in MQT we can indicate the version of the webkit that we need. So that in this way MQT always will be in charge of deciding where to download the webkit.

**Comment by JesusZapata** [comment]
@suniagajose 
Could do you check this PR https://github.com/Vauxoo/maintainer-quality-tools/pull/205/ 
And approve this changes
