### ISSUE TITLE
Pulling wrong repos when adding a oca dependency for a owner different from vauxoo

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/maintainer-quality-tools#215]
I added stock-logistic-warehouse repository to the oca_dependencies of a private customer project in Vauxoo as is shows in the next image

![image](https://user-images.githubusercontent.com/7593953/28092490-8dc73c5e-6661-11e7-8277-3f76c20647d2.png)

As you can see I added stock-logistic-warehouse repository as OCA owner instead of Vauxoo, this because in that moment the Vauxoo repository does not have 10.0 branch (this change... now vauxoo has oca/10.0 repo forks updated). Thanks to this last state I found out the next error in runbot and travis

![image](https://user-images.githubusercontent.com/7593953/28064813-08897172-6604-11e7-8456-eb9df32739f2.png)

It checked oca/10.0 oca_dependencies file and I found out that the oca_dependencies does not contain the  remote information https://github.com/OCA/stock-logistics-warehouse/blob/10.0/oca_dependencies.txt
![image](https://user-images.githubusercontent.com/7593953/28125031-64978ef0-66f3-11e7-98c8-bd03693143cc.png)

I think that maybe this lack of remote info in the oca_dependencies file is making that mqt scripts take the main project owner, instead the dependency owner: the correct owner/repos are not the ones that are pulled with mqt. Thanks to this we would have a not properly configured environment.

**Comment by zaoral** [comment]
cc @JesusZapata @moylop260

**Comment by moylop260** [comment]
@tomeyro 
Could you consider this case for MQT is very similar to https://git.vauxoo.com/vauxoo/deployv/issues/204?

And migrate the fix of deployv https://git.vauxoo.com/vauxoo/deployv/issues/204 to MQT please

**Comment by zaoral** [comment]
Hi @tomeyro 
The fix related to this issues has been applied?

**Comment by tomeyro** [comment]
@zaoral The PR (https://github.com/Vauxoo/maintainer-quality-tools/pull/216) is still being reviewed. It should be merged soon. I'll check on it.

**Comment by zaoral** [comment]
@tomeyro ok. thank you @tomeyro

**Comment by luisg123v** [comment]
Already solved by adding variable `TRAVIS_REPO_SLUG` to the project template, so closing.
