### ISSUE TITLE
Error when index file is empty

### ISSUE THREAD

**Issue by luistorresm** [Vauxoo/maintainer-quality-tools#259]
When a module have the index file empty, and you try read the module description you get the next error:

![aplicaciones odoo](https://user-images.githubusercontent.com/7606656/34446467-d7bb116c-eca0-11e7-93cb-0b637a6fff80.png)

We could get a lint error when the index file is added but is empty?

**Comment by luistorresm** [comment]
FYI @moylop260 @JesusZapata

**Comment by moylop260** [comment]
Could you create the issue to odoo/odoo, please?

wont fix from mqt
