### ISSUE TITLE
Warnings in travis are returning green build

### ISSUE THREAD

**Issue by umiphos** [Vauxoo/maintainer-quality-tools#260]
If there are a lot of warning in travis the build will be passed as green, that's a problem because if you(for example) put to write a field that does not exist, that is not an error, it's a warning and we can get a false green in production.

![Image of a false green](https://user-images.githubusercontent.com/4094256/35582503-a54706be-05b4-11e8-9c7f-6f108fd10be2.png)

Prof
https://travis-ci.com/Vauxoo/odoo-peru/jobs/108227260

**Comment by luisg123v** [comment]
@umiphos 
When there are warnings, Runbot fails, which in turn would cause the CI to report a failure.

**Comment by luisg123v** [comment]
We don't use Travis anymore and we support warnings on GitLab CI, so closing.
