### ISSUE TITLE
[IMP] travis_weblate: Add compatibility with gitlab

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/maintainer-quality-tools#265]
We need that the [travis_weblate](https://github.com/Vauxoo/maintainer-quality-tools/blob/master/travis/travis_weblate.py) script works with gitlab.

Maybe It was a bad idea uses github api to create a commit instead of use 100% `git` commands and generate a full compatibility with all `git` hosts.

**Comment by luisg123v** [comment]
Wow, you're right, assuming GitHub from the beginning was quite not a good idea. As I see it, the class `GitHubApi` needs to be mostly refactored.

**Comment by moylop260** [comment]
@luisg123v Any news about this issue?

We have migrated all projects to gitlab then it is important fix this feature.

**Comment by luisg123v** [comment]
Sorry @moylop260 I've not made any progress on this.

This is an issue that requires time, and I'm currently working on several other ones, which let me no too much time to solve this.

Would you consider assigning this to someone else?

**Comment by moylop260** [comment]
We can wait for you...
Don't worry.
