### ISSUE TITLE
Changed modules are lint-tested even if they're on $EXCLUDE_LINT

### ISSUE THREAD

**Issue by JonathanOsAlc** [Vauxoo/maintainer-quality-tools#290]
When the test lint is running, the module `shopify_ept` isn't ignored and that module was specified to be ignored.

![image](https://user-images.githubusercontent.com/17712814/44435713-d4d12380-a576-11e8-80be-2fc1f80e83be.png)

**Comment by tomeyro** [comment]
@moylop260 @luisg123v Could you help us with this?

After the latest fixes the Amazon module stopped raising errors,  
but then after updating some things in the shopify module it started  
raising this errors even when it shows that is ignoring the module.

**Comment by luisg123v** [comment]
@tomeyro 
Please provide a link to the MR where the error is reproduced.

**Comment by tomeyro** [comment]
@luisg123v https://git.vauxoo.com/vauxoo/qualifirst/merge_requests/311

**Comment by luisg123v** [comment]
Also take into account that, even if you ignore a module, when you change it in a MR, lints will be shown for that module. That's because modified modules are always lint-checked.

**Comment by tomeyro** [comment]
@luisg123v Then what is the point of ignoring it?

The mentioned module was provided and is maintained by a third party,  
if the third party makes a fix (or we make a quick fix for it) the module will  
be shown as "modified". We still need the module to be ignored after this,  
the code base is still theirs and they don't work with our standards.

**Comment by luisg123v** [comment]
@JonathanOsAlc  
Could you change the title? To:  
Changed modules are lint-tested even if they're on $EXCLUDE_LINT
