### ISSUE TITLE
The script test_odoo_lint not find the path of rst2html

### ISSUE THREAD

**Issue by yaniaular** [Vauxoo/maintainer-quality-tools#30]
**Problem**

I try run the script test_odoo_lint, but to review README.rst occur a error respect to rst2html.

**Solution**

The temporal solution for me is the next:

<pre>
$ which rst2html
     /usr/bin/rst2html
</pre>

and change line 288 of test_odoo_lint:
<pre>
-             ['rst2html.py', os.path.join(root, filename),
+             ['/usr/bin/rst2html', os.path.join(root, filename),
</pre>
I recommend you use the "which" command in your code to determine the path of rst2html.

**Error in console**

[odoo_lint][INFO] crm_claim_categ_as_name: Checking documentation
[odoo_lint][INFO] Checking module: product_warranty
[odoo_lint][INFO] product_warranty: Checking description
Traceback (most recent call last):
  File "./test_odoo_lint", line 344, in <module>
    main()
  File "./test_odoo_lint", line 340, in main
    obj.run()
  File "./test_odoo_lint", line 202, in run
    self.check_description(root, module, filenames)
  File "./test_odoo_lint", line 269, in check_description
    if self.check_rst_syntax(root, module, 'README.rst'):
  File "./test_odoo_lint", line 291, in check_rst_syntax
    stdout=subprocess.PIPE).stdout.read()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by yaniaular** [comment]
@moylop260

**Comment by moylop260** [comment]
@zaoral 
We can add this section of code to get full path of binaries files of:
https://github.com/odoo/odoo/blob/8.0/openerp/tools/misc.py#L72-L79

This work multi-OS.

**Comment by zaoral** [comment]
Hello @yaniaular @moylop260 
I wll start working in this issue at Task [vx#3932](https://www.vauxoo.com/web#id=3932&view_type=form&model=project.task&action=138)

**Comment by moylop260** [comment]
Workin in https://github.com/Vauxoo/maintainer-quality-tools/pull/32

**Comment by zaoral** [comment]
@moylop260 this issues was resolve?
