### ISSUE TITLE
Add new test checks to the test_odoo_lint

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/maintainer-quality-tools#33]
New checks wil be added to improve the odoo lint test. This new checks will be marked as warnings for the moment to avoid any problem with a red travis will the migration of the new rules and templates is fullfil:

- check that the index.html exist for the module description
- check that all the modules have a documentation folder and and index.rst file (already check the file is exist, now add check that the field exist.
- check that the readme.rst file have the next template with all the sections defiend in https://github.com/Vauxoo/maintainer-tools/tree/master/template/module. Skype the Maintener section when exporting to the index.html file.

**Comment by moylop260** [comment]
This is fixed
