### ISSUE TITLE
Update the todo_odoo_lint to check the structure of the rst file

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/maintainer-quality-tools#34]
Check that respect the next template: https://github.com/Vauxoo/maintainer-tools/tree/master/template/module

Please add this functionality with an standard library, preference with docutils.

For the moment add this as an warning instead of a error to avoid a red travis. 

NOTE: The maintainer section will not be take into account when generating the index.html file from the vauxoo-dev/gist-vauxoo/description2html script.

Best Regards.

**Comment by moylop260** [comment]
rst check now is in pylint-odoo package
