### ISSUE TITLE
pre-commit: pylint,eslint - Add feature to disable checks using environment variable

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/maintainer-quality-tools#340]
Each vauxoo project can decide to disable a few checks

It could be interesting to be able to use an environment variable to disable them

Very similar to the feature to exclude modules or files:
 - https://github.com/Vauxoo/maintainer-quality-tools/pull/331/files

But this time to disable a enabled check from:
 - https://github.com/Vauxoo/maintainer-quality-tools/blob/58e689e7af3cade19596ec533206c49a57c1e17b/travis/cfg/precommit/.pylintrc#L18-L19

Or 
 - https://github.com/Vauxoo/maintainer-quality-tools/blob/58e689e7af3cade19596ec533206c49a57c1e17b/travis/cfg/precommit/.pylintrc-optional#L21-L22

I'm not sure what is the better option if parsing the configuration file to disable the check
or modifying the pylint command of the pre-commit to `disable=checks`

The name of the variable could be `PYLINT_DISABLE_CHECKS=check-name1,check-name2`

Consider create a dummy MR using a real project

**Comment by antonag32** [comment]
@moylop260
I implemented your requested changes and created a PR accordingly. However I don't understand the last part about a dummy MR. I tested the changes locally and they do work, do you want me to implement a Github Action on a repository and run pre-commit with my changes to verify checks are disabled?

**Comment by luisg123v** [comment]
Hi @antonag32,

What @moylop260 means is, to test your changes, you should use your dev branch on a real project.

You can check [this](https://git.vauxoo.com/vauxoo/l10n-mx-payroll/-/merge_requests/395) as an example (it was used to test [this](https://github.com/Vauxoo/maintainer-quality-tools/pull/326))

Regards,
