### ISSUE TITLE
Use commit message tags to stop running some CI-services

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/maintainer-quality-tools#96]
All the time we need to submit pull requests when doing a development but every push done, triggers all known CI-services,  I think may be helpful to use some commit message parsing (dummy ones) to disable some features and no load servers if is not required.
e.g.

> With the tag [no_runbot] we may be avoid unnecessary server load when is not required.

`[IMP][no_runbot] module_name: remove some unneeded things`

And with this, the necessary check (we should be disabling there, required to be merged) should be red (of course), because that validation did not run normally. This also implies that after all feature detailed in the PR description a `git rebase` squash or reword should be apply in order to follow guidelines for commit messages and clean them up and finally run CI-services as expected.

**Comment by moylop260** [comment]
@osvalr 
Yor proposal is like as [Skipping-a-build](https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build)
IMHO We shouldn't use commit message to change the flow of a CI

But we can wait other opinion.

**Comment by osvalr** [comment]
ok, Travis-CI is stoppable, Runbot isn't. I know, that's the idea.
I didn't know that exists by the way.
