### ISSUE TITLE
ImportError: No module named babel.dates

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/maintainer-quality-tools#98]
(Click in the image to see full travis log)
[![image](https://cloud.githubusercontent.com/assets/2961943/14340036/1ea69196-fc4d-11e5-8e1e-47486fb0ba36.png)](https://travis-ci.com/Vauxoo/yoytec/jobs/36962015)

PS: Maybe is not the right repo to make this issue

**Comment by moylop260** [comment]
travis error using pip cache
I fixed it deleting all cache from travis
